//THIS FILE IS AUTOGENERATED BY GHOSTCOMPILER. DON'T MODIFY OR ALTER.
using System;
using AOT;
using Unity.Burst;
using Unity.Networking.Transport;
using Unity.NetCode.LowLevel.Unsafe;
using Unity.Collections.LowLevel.Unsafe;
using Unity.Entities;
using Unity.Collections;
using Unity.NetCode;
using Unity.Transforms;
using Unity.Mathematics;

namespace Assembly_CSharp.Generated
{
    [BurstCompile]
    public struct FPSdemoGunManager_PlayerGunDataGhostComponentSerializer
    {
        static GhostComponentSerializer.State GetState()
        {
            // This needs to be lazy initialized because otherwise there is a depenency on the static initialization order which breaks il2cpp builds due to TYpeManager not being initialized yet
            if (!s_StateInitialized)
            {
                s_State = new GhostComponentSerializer.State
                {
                    GhostFieldsHash = 5104797891130893214,
                    ExcludeFromComponentCollectionHash = 0,
                    ComponentType = ComponentType.ReadWrite<FPSdemo.GunManager.PlayerGunData>(),
                    ComponentSize = UnsafeUtility.SizeOf<FPSdemo.GunManager.PlayerGunData>(),
                    SnapshotSize = UnsafeUtility.SizeOf<Snapshot>(),
                    ChangeMaskBits = ChangeMaskBits,
                    SendMask = GhostComponentSerializer.SendMask.Interpolated | GhostComponentSerializer.SendMask.Predicted,
                    SendToOwner = SendToOwnerType.All,
                    SendForChildEntities = 1,
                    VariantHash = 0,
                    CopyToSnapshot =
                        new PortableFunctionPointer<GhostComponentSerializer.CopyToFromSnapshotDelegate>(CopyToSnapshot),
                    CopyFromSnapshot =
                        new PortableFunctionPointer<GhostComponentSerializer.CopyToFromSnapshotDelegate>(CopyFromSnapshot),
                    RestoreFromBackup =
                        new PortableFunctionPointer<GhostComponentSerializer.RestoreFromBackupDelegate>(RestoreFromBackup),
                    PredictDelta = new PortableFunctionPointer<GhostComponentSerializer.PredictDeltaDelegate>(PredictDelta),
                    CalculateChangeMask =
                        new PortableFunctionPointer<GhostComponentSerializer.CalculateChangeMaskDelegate>(
                            CalculateChangeMask),
                    Serialize = new PortableFunctionPointer<GhostComponentSerializer.SerializeDelegate>(Serialize),
                    Deserialize = new PortableFunctionPointer<GhostComponentSerializer.DeserializeDelegate>(Deserialize),
                    #if UNITY_EDITOR || DEVELOPMENT_BUILD
                    ReportPredictionErrors = new PortableFunctionPointer<GhostComponentSerializer.ReportPredictionErrorsDelegate>(ReportPredictionErrors),
                    #endif
                };
                #if UNITY_EDITOR || DEVELOPMENT_BUILD
                s_State.NumPredictionErrorNames = GetPredictionErrorNames(ref s_State.PredictionErrorNames);
                #endif
                s_StateInitialized = true;
            }
            return s_State;
        }
        private static bool s_StateInitialized;
        private static GhostComponentSerializer.State s_State;
        public static GhostComponentSerializer.State State => GetState();
        public struct Snapshot
        {
            public int gunTypeIndex;
            public float changeGunGap;
            public int gunstate;
            public int rotation_ValueX;
            public int rotation_ValueY;
            public int rotation_ValueZ;
            public int rotation_ValueW;
        }
        public const int ChangeMaskBits = 4;
        [BurstCompile]
        [MonoPInvokeCallback(typeof(GhostComponentSerializer.CopyToFromSnapshotDelegate))]
        private static void CopyToSnapshot(IntPtr stateData, IntPtr snapshotData, int snapshotOffset, int snapshotStride, IntPtr componentData, int componentStride, int count)
        {
            for (int i = 0; i < count; ++i)
            {
                ref var snapshot = ref GhostComponentSerializer.TypeCast<Snapshot>(snapshotData, snapshotOffset + snapshotStride*i);
                ref var component = ref GhostComponentSerializer.TypeCast<FPSdemo.GunManager.PlayerGunData>(componentData, componentStride*i);
                ref var serializerState = ref GhostComponentSerializer.TypeCast<GhostSerializerState>(stateData, 0);
                snapshot.gunTypeIndex = (int) component.gunTypeIndex;
                snapshot.changeGunGap = component.changeGunGap;
                snapshot.gunstate = (int) component.gunstate;
                snapshot.rotation_ValueX = (int)math.round(component.rotation.Value.value.x * 1000);
                snapshot.rotation_ValueY = (int)math.round(component.rotation.Value.value.y * 1000);
                snapshot.rotation_ValueZ = (int)math.round(component.rotation.Value.value.z * 1000);
                snapshot.rotation_ValueW = (int)math.round(component.rotation.Value.value.w * 1000);
            }
        }
        [BurstCompile]
        [MonoPInvokeCallback(typeof(GhostComponentSerializer.CopyToFromSnapshotDelegate))]
        private static void CopyFromSnapshot(IntPtr stateData, IntPtr snapshotData, int snapshotOffset, int snapshotStride, IntPtr componentData, int componentStride, int count)
        {
            for (int i = 0; i < count; ++i)
            {
                var deserializerState = GhostComponentSerializer.TypeCast<GhostDeserializerState>(stateData, 0);
                ref var snapshotInterpolationData = ref GhostComponentSerializer.TypeCast<SnapshotData.DataAtTick>(snapshotData, snapshotStride*i);
                ref var snapshotBefore = ref GhostComponentSerializer.TypeCast<Snapshot>(snapshotInterpolationData.SnapshotBefore, snapshotOffset);
                ref var snapshotAfter = ref GhostComponentSerializer.TypeCast<Snapshot>(snapshotInterpolationData.SnapshotAfter, snapshotOffset);
                //Compute the required owner mask for the components and buffers by retrievieng the ghost owner id from the data for the current tick.
                if (snapshotInterpolationData.GhostOwner > 0)
                {
                    var requiredOwnerMask = snapshotInterpolationData.GhostOwner == deserializerState.GhostOwner
                        ? SendToOwnerType.SendToOwner
                        : SendToOwnerType.SendToNonOwner;
                    if ((deserializerState.SendToOwner & requiredOwnerMask) == 0)
                        continue;
                }
                deserializerState.SnapshotTick = snapshotInterpolationData.Tick;
                float snapshotInterpolationFactorRaw = snapshotInterpolationData.InterpolationFactor;
                float snapshotInterpolationFactor = snapshotInterpolationFactorRaw;
                ref var component = ref GhostComponentSerializer.TypeCast<FPSdemo.GunManager.PlayerGunData>(componentData, componentStride*i);
                component.gunTypeIndex = (int) snapshotBefore.gunTypeIndex;
                component.changeGunGap = snapshotBefore.changeGunGap;
                component.gunstate = (FPSdemo.Gunstate) snapshotBefore.gunstate;
                snapshotInterpolationFactor = snapshotInterpolationFactorRaw;
                var rotation_Value_Before = math.normalize(new quaternion(snapshotBefore.rotation_ValueX * 0.001f, snapshotBefore.rotation_ValueY * 0.001f, snapshotBefore.rotation_ValueZ * 0.001f, snapshotBefore.rotation_ValueW * 0.001f));
                var rotation_Value_After = math.normalize(new quaternion(snapshotAfter.rotation_ValueX * 0.001f, snapshotAfter.rotation_ValueY * 0.001f, snapshotAfter.rotation_ValueZ * 0.001f, snapshotAfter.rotation_ValueW * 0.001f));
                component.rotation.Value = math.slerp(rotation_Value_Before,
                    rotation_Value_After, snapshotInterpolationFactor);

            }
        }


        [BurstCompile]
        [MonoPInvokeCallback(typeof(GhostComponentSerializer.RestoreFromBackupDelegate))]
        private static void RestoreFromBackup(IntPtr componentData, IntPtr backupData)
        {
            ref var component = ref GhostComponentSerializer.TypeCast<FPSdemo.GunManager.PlayerGunData>(componentData, 0);
            ref var backup = ref GhostComponentSerializer.TypeCast<FPSdemo.GunManager.PlayerGunData>(backupData, 0);
            component.gunTypeIndex = backup.gunTypeIndex;
            component.changeGunGap = backup.changeGunGap;
            component.gunstate = backup.gunstate;
            component.rotation.Value = backup.rotation.Value;
        }

        [BurstCompile]
        [MonoPInvokeCallback(typeof(GhostComponentSerializer.PredictDeltaDelegate))]
        private static void PredictDelta(IntPtr snapshotData, IntPtr baseline1Data, IntPtr baseline2Data, ref GhostDeltaPredictor predictor)
        {
            ref var snapshot = ref GhostComponentSerializer.TypeCast<Snapshot>(snapshotData);
            ref var baseline1 = ref GhostComponentSerializer.TypeCast<Snapshot>(baseline1Data);
            ref var baseline2 = ref GhostComponentSerializer.TypeCast<Snapshot>(baseline2Data);
            snapshot.gunTypeIndex = predictor.PredictInt(snapshot.gunTypeIndex, baseline1.gunTypeIndex, baseline2.gunTypeIndex);
            snapshot.gunstate = predictor.PredictInt(snapshot.gunstate, baseline1.gunstate, baseline2.gunstate);
            snapshot.rotation_ValueX = predictor.PredictInt(snapshot.rotation_ValueX, baseline1.rotation_ValueX, baseline2.rotation_ValueX);
            snapshot.rotation_ValueY = predictor.PredictInt(snapshot.rotation_ValueY, baseline1.rotation_ValueY, baseline2.rotation_ValueY);
            snapshot.rotation_ValueZ = predictor.PredictInt(snapshot.rotation_ValueZ, baseline1.rotation_ValueZ, baseline2.rotation_ValueZ);
            snapshot.rotation_ValueW = predictor.PredictInt(snapshot.rotation_ValueW, baseline1.rotation_ValueW, baseline2.rotation_ValueW);
        }
        [BurstCompile]
        [MonoPInvokeCallback(typeof(GhostComponentSerializer.CalculateChangeMaskDelegate))]
        private static void CalculateChangeMask(IntPtr snapshotData, IntPtr baselineData, IntPtr bits, int startOffset)
        {
            ref var snapshot = ref GhostComponentSerializer.TypeCast<Snapshot>(snapshotData);
            ref var baseline = ref GhostComponentSerializer.TypeCast<Snapshot>(baselineData);
            uint changeMask;
            changeMask = (snapshot.gunTypeIndex != baseline.gunTypeIndex) ? 1u : 0;
            changeMask |= (snapshot.changeGunGap != baseline.changeGunGap) ? (1u<<1) : 0;
            changeMask |= (snapshot.gunstate != baseline.gunstate) ? (1u<<2) : 0;
            changeMask |= (snapshot.rotation_ValueX != baseline.rotation_ValueX ||
                        snapshot.rotation_ValueY != baseline.rotation_ValueY ||
                        snapshot.rotation_ValueZ != baseline.rotation_ValueZ ||
                        snapshot.rotation_ValueW != baseline.rotation_ValueW) ? (1u<<3) : 0;
            GhostComponentSerializer.CopyToChangeMask(bits, changeMask, startOffset, 4);
        }
        [BurstCompile]
        [MonoPInvokeCallback(typeof(GhostComponentSerializer.SerializeDelegate))]
        private static void Serialize(IntPtr snapshotData, IntPtr baselineData, ref DataStreamWriter writer, ref NetworkCompressionModel compressionModel, IntPtr changeMaskData, int startOffset)
        {
            ref var snapshot = ref GhostComponentSerializer.TypeCast<Snapshot>(snapshotData);
            ref var baseline = ref GhostComponentSerializer.TypeCast<Snapshot>(baselineData);
            uint changeMask = GhostComponentSerializer.CopyFromChangeMask(changeMaskData, startOffset, ChangeMaskBits);
            if ((changeMask & (1 << 0)) != 0)
                writer.WritePackedIntDelta(snapshot.gunTypeIndex, baseline.gunTypeIndex, compressionModel);
            if ((changeMask & (1 << 1)) != 0)
                writer.WritePackedFloatDelta(snapshot.changeGunGap, baseline.changeGunGap, compressionModel);
            if ((changeMask & (1 << 2)) != 0)
                writer.WritePackedIntDelta(snapshot.gunstate, baseline.gunstate, compressionModel);
            if ((changeMask & (1 << 3)) != 0)
            {
                writer.WritePackedIntDelta(snapshot.rotation_ValueX, baseline.rotation_ValueX, compressionModel);
                writer.WritePackedIntDelta(snapshot.rotation_ValueY, baseline.rotation_ValueY, compressionModel);
                writer.WritePackedIntDelta(snapshot.rotation_ValueZ, baseline.rotation_ValueZ, compressionModel);
                writer.WritePackedIntDelta(snapshot.rotation_ValueW, baseline.rotation_ValueW, compressionModel);
            }
        }
        [BurstCompile]
        [MonoPInvokeCallback(typeof(GhostComponentSerializer.DeserializeDelegate))]
        private static void Deserialize(IntPtr snapshotData, IntPtr baselineData, ref DataStreamReader reader, ref NetworkCompressionModel compressionModel, IntPtr changeMaskData, int startOffset)
        {
            ref var snapshot = ref GhostComponentSerializer.TypeCast<Snapshot>(snapshotData);
            ref var baseline = ref GhostComponentSerializer.TypeCast<Snapshot>(baselineData);
            uint changeMask = GhostComponentSerializer.CopyFromChangeMask(changeMaskData, startOffset, ChangeMaskBits);
            if ((changeMask & (1 << 0)) != 0)
                snapshot.gunTypeIndex = reader.ReadPackedIntDelta(baseline.gunTypeIndex, compressionModel);
            else
                snapshot.gunTypeIndex = baseline.gunTypeIndex;
            if ((changeMask & (1 << 1)) != 0)
                snapshot.changeGunGap = reader.ReadPackedFloatDelta(baseline.changeGunGap, compressionModel);
            else
                snapshot.changeGunGap = baseline.changeGunGap;
            if ((changeMask & (1 << 2)) != 0)
                snapshot.gunstate = reader.ReadPackedIntDelta(baseline.gunstate, compressionModel);
            else
                snapshot.gunstate = baseline.gunstate;
            if ((changeMask & (1 << 3)) != 0)
            {
                snapshot.rotation_ValueX = reader.ReadPackedIntDelta(baseline.rotation_ValueX, compressionModel);
                snapshot.rotation_ValueY = reader.ReadPackedIntDelta(baseline.rotation_ValueY, compressionModel);
                snapshot.rotation_ValueZ = reader.ReadPackedIntDelta(baseline.rotation_ValueZ, compressionModel);
                snapshot.rotation_ValueW = reader.ReadPackedIntDelta(baseline.rotation_ValueW, compressionModel);
            }
            else
            {
                snapshot.rotation_ValueX = baseline.rotation_ValueX;
                snapshot.rotation_ValueY = baseline.rotation_ValueY;
                snapshot.rotation_ValueZ = baseline.rotation_ValueZ;
                snapshot.rotation_ValueW = baseline.rotation_ValueW;
            }
        }
        #if UNITY_EDITOR || DEVELOPMENT_BUILD
        [BurstCompile]
        [MonoPInvokeCallback(typeof(GhostComponentSerializer.ReportPredictionErrorsDelegate))]
        private static void ReportPredictionErrors(IntPtr componentData, IntPtr backupData, ref UnsafeList<float> errors)
        {
            ref var component = ref GhostComponentSerializer.TypeCast<FPSdemo.GunManager.PlayerGunData>(componentData, 0);
            ref var backup = ref GhostComponentSerializer.TypeCast<FPSdemo.GunManager.PlayerGunData>(backupData, 0);
            int errorIndex = 0;
            errors[errorIndex] = math.max(errors[errorIndex], math.abs(component.gunTypeIndex - backup.gunTypeIndex));
            ++errorIndex;
            errors[errorIndex] = math.max(errors[errorIndex], math.abs(component.changeGunGap - backup.changeGunGap));
            ++errorIndex;
            errors[errorIndex] = math.max(errors[errorIndex], math.abs(component.gunstate - backup.gunstate));
            ++errorIndex;
            errors[errorIndex] = math.max(errors[errorIndex], math.distance(component.rotation.Value.value, backup.rotation.Value.value));
            ++errorIndex;
        }
        private static int GetPredictionErrorNames(ref FixedString512 names)
        {
            int nameCount = 0;
            if (nameCount != 0)
                names.Append(new FixedString32(","));
            names.Append(new FixedString64("gunTypeIndex"));
            ++nameCount;
            if (nameCount != 0)
                names.Append(new FixedString32(","));
            names.Append(new FixedString64("changeGunGap"));
            ++nameCount;
            if (nameCount != 0)
                names.Append(new FixedString32(","));
            names.Append(new FixedString64("gunstate"));
            ++nameCount;
            if (nameCount != 0)
                names.Append(new FixedString32(","));
            names.Append(new FixedString64("rotation.Value"));
            ++nameCount;
            return nameCount;
        }
        #endif
    }
}
