//THIS FILE IS AUTOGENERATED BY GHOSTCOMPILER. DON'T MODIFY OR ALTER.
using Unity.Entities;
using Unity.NetCode;
using Assembly_CSharp.Generated;

namespace Assembly_CSharp.Generated
{
    [UpdateInGroup(typeof(ClientAndServerInitializationSystemGroup))]
    public class GhostComponentSerializerRegistrationSystem : SystemBase
    {
        protected override void OnCreate()
        {
            var ghostCollectionSystem = World.GetOrCreateSystem<GhostCollectionSystem>();
            ghostCollectionSystem.AddSerializer(CharacterControllerComponentDataGhostComponentSerializer.State);
            ghostCollectionSystem.AddSerializer(CharacterControllerInternalDataGhostComponentSerializer.State);
            ghostCollectionSystem.AddSerializer(PointGhostComponentSerializer.State);
            ghostCollectionSystem.AddSerializer(FPSdemoEnemyGhostComponentSerializer.State);
            ghostCollectionSystem.AddSerializer(FPSdemoEnemyBossGhostComponentSerializer.State);
            ghostCollectionSystem.AddSerializer(FPSdemoMissleBossGhostComponentSerializer.State);
            ghostCollectionSystem.AddSerializer(FPSdemoGunManager_PlayerGunDataGhostComponentSerializer.State);
            ghostCollectionSystem.AddSerializer(FPSdemoGunManager_PlayerGunInternalDataGhostComponentSerializer.State);
            ghostCollectionSystem.AddSerializer(FPSdemoGunManager_ShootEventDataGhostComponentSerializer.State);
            ghostCollectionSystem.AddSerializer(FPSdemoHealthDataGhostComponentSerializer.State);
        }

        protected override void OnUpdate()
        {
            var parentGroup = World.GetExistingSystem<InitializationSystemGroup>();
            if (parentGroup != null)
            {
                parentGroup.RemoveSystemFromUpdateList(this);
            }
        }
    }
}